
language: node_js
node_js:
   - "node"
   - "4.0"
   - "0.12"
   - "0.10"

# The following is for tape-run.
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
